name: bloc_firebase_login
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  equatable: 2.0.5
  firebase_auth: 3.10.0
  firebase_core: 1.23.0
  google_sign_in: 5.4.2
  flutter_bloc: 8.1.1
  cloud_firestore: 3.4.9
  formz: 0.4.1
  uuid: 3.0.6
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

