name: crudbloc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  equatable: 2.0.5
  flutter_bloc: 8.1.1
  formz: 0.4.1
  rxdart: 0.27.5
  flutter_secure_storage: 6.0.0
  dio: 4.0.6
  introduction_screen: 3.0.2
  flutter_svg: 1.1.5
  eva_icons_flutter: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

