name: bloc_ril_api_login
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.1.1
  equatable: 2.0.5
  dio: 4.0.6
  form_validator: 1.0.2
  get_storage: 2.0.3
  formz: 0.4.1
  salomon_bottom_bar: 3.3.1
  jwt_decoder: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

